DIR=dir
MALICIOUS_DIR=malicious_dir
INTERVAL_SECS=5

pre-build:
	mkdir -p ($MALICIOUS_DIR)
antivirus: pre-build
	bash antivirusd.sh ($DIR) ($MALICIOUS_DIR) ($INTERVAL_SECS)
restore: pre-build
	bash restore.sh ($DIR) ($MALICIOUS_DIR)
